# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build Jobs with 2 scripts
    steps:
    - script: echo "Hello I am job step ONE for NPM INSTALL"
    - script: echo "Hello I am job step TWO for NPM RUN BUILD"
  #  - script: npm install
  #  - script: npm run build
- stage: Test
  - job: Test-Jobs-Scripts
    displayName: Test Jobs with 1 scripts
    steps:
    - script: echo "Hello I am job step THREE for NPM TEST"
  #  - script: npm test
  
- stage: Run
  jobs:
  - job: Run
    displayName: Run jobs using Maven
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: "JaCoCo"
        summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
        reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
        failIfCoverageEmpty: true
    
    - script: |
        echo Starting the build
        mvn package
      displayName: 'Build with Maven using SCRIPT Step'
